### ISSUE TITLE
Subscription macaroon  mismatch

### ISSUE THREAD

**Issue by pooyadav** [me-box/lib-python-databox#9]
Macaroon is not verified currently in  store-json when connected through websocket to store-json.

/node_modules/macaroons.js/lib/MacaroonsDeSerializer.js:107
            throw new Error("Not enough data bytes available. Needed " + data.length + " bytes, but was only " + read);
            ^

Error: Not enough data bytes available. Needed 92 bytes, but was only 62
    at Function.MacaroonsDeSerializer.readPacket (/node_modules/macaroons.js/lib/MacaroonsDeSerializer.js:107:19)
    at Function.MacaroonsDeSerializer.deserializeStream (/node_modules/macaroons.js/lib/MacaroonsDeSerializer.js:39:58)
    at Function.MacaroonsDeSerializer.deserialize (/node_modules/macaroons.js/lib/MacaroonsDeSerializer.js:30:38)
    at Function.MacaroonsBuilder.deserialize (/node_modules/macaroons.js/lib/MacaroonsBuilder.js:61:38)
    at Object.<anonymous> (/src/lib/macaroon/macaroon-verifier.js:206:41)
    at WebSocketServer.handleHybiUpgrade (/node_modules/ws/lib/WebSocketServer.js:322:20)
    at WebSocketServer.handleUpgrade (/node_modules/ws/lib/WebSocketServer.js:173:26)
    at Server.WebSocketServer._onServerUpgrade (/node_modules/ws/lib/WebSocketServer.js:89:12)
    at emitThree (events.js:136:13)
    at Server.emit (events.js:217:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! store-json@1.0.0 start: `node ./src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the store-json@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pooyadav** [comment]
Resolved by https://github.com/me-box/lib-python-databox/pull/10/
Macaroons from arbiter are "utf-8" encoded when received as response data. Therefore to send over websocket, that required .decode("utf-8") before sending as "base64".
